/**
 * Mission Control Explorer — AI Insights Panel
 * Renders pre-generated AI analysis from data/insights/*.json
 */

(function () {
  'use strict';

  const insightsCache = {};

  window.renderInsights = async function (reportDate) {
    const container = document.getElementById('insightsContainer');
    if (!container) return;

    if (!reportDate) {
      container.innerHTML = '<div class="no-insights"><h3>No Report Selected</h3><p>Select a report from the sidebar to view AI analysis.</p></div>';
      return;
    }

    // Try to load pre-generated insights
    const insights = await loadInsights(reportDate);

    if (!insights) {
      // Generate on-the-fly from RAG history
      const ragHistory = window.explorerState?.ragHistory;
      if (ragHistory) {
        renderGeneratedInsights(container, reportDate, ragHistory);
      } else {
        container.innerHTML = `<div class="no-insights"><h3>No AI Insights Available</h3><p>No pre-generated insights for ${window.formatDate(reportDate)}.</p><p>Run <code>python3 generate-insights.py</code> to generate.</p></div>`;
      }
      return;
    }

    renderInsightsFromData(container, insights);
  };

  async function loadInsights(date) {
    if (insightsCache[date]) return insightsCache[date];

    try {
      const res = await fetch(`data/insights/${date}.json`);
      if (!res.ok) return null;
      const data = await res.json();
      insightsCache[date] = data;
      return data;
    } catch {
      return null;
    }
  }

  function renderInsightsFromData(container, data) {
    let html = '';

    html += '<div class="insights-header">';
    html += '<h2>AI Analysis</h2>';
    html += `<div class="insights-date">${data.date || ''} &middot; Generated by Claude</div>`;
    html += '</div>';

    // Executive Summary
    if (data.executive_summary) {
      html += '<div class="insight-section">';
      html += '<div class="insight-section-title">Executive Summary</div>';
      html += `<div class="insight-card summary">${data.executive_summary}</div>`;
      html += '</div>';
    }

    // Trends
    if (data.trends && data.trends.length > 0) {
      html += '<div class="insight-section">';
      html += '<div class="insight-section-title">Country Trends</div>';
      data.trends.forEach((t) => {
        const severity = t.severity || 'neutral';
        html += `<div class="insight-card ${severity}">`;
        html += `<span class="insight-country">${t.country}:</span> ${t.insight}`;
        html += '</div>';
      });
      html += '</div>';
    }

    // Predictions
    if (data.predictions && data.predictions.length > 0) {
      html += '<div class="insight-section">';
      html += '<div class="insight-section-title">Predictions</div>';
      data.predictions.forEach((p) => {
        const severity = p.confidence === 'high' ? 'positive' : p.confidence === 'low' ? 'warning' : 'neutral';
        html += `<div class="insight-card ${severity}">`;
        html += `<span class="insight-country">${p.country}:</span> ${p.prediction}`;
        html += `<span class="insight-confidence">${p.confidence} confidence</span>`;
        html += '</div>';
      });
      html += '</div>';
    }

    // Coaching
    if (data.coaching && data.coaching.length > 0) {
      html += '<div class="insight-section">';
      html += '<div class="insight-section-title">Leadership Coaching</div>';
      data.coaching.forEach((c) => {
        html += `<div class="insight-coaching">${c}</div>`;
      });
      html += '</div>';
    }

    // Risk Watch
    if (data.risk_watch && data.risk_watch.length > 0) {
      html += '<div class="insight-section">';
      html += '<div class="insight-section-title">Risk Watch</div>';
      data.risk_watch.forEach((r) => {
        html += `<div class="insight-card warning">${r}</div>`;
      });
      html += '</div>';
    }

    container.innerHTML = html;
  }

  // ===== Auto-generated insights from RAG data =====

  function renderGeneratedInsights(container, reportDate, ragHistory) {
    const data = ragHistory;
    const reports = data.reports;
    const dateIndex = reports.indexOf(reportDate);

    const TRACKED = [
      'India', 'Malaysia', 'KSA', 'Belgium', 'Croatia',
      'Poland', 'UAE', 'Germany', 'France', 'Singapore',
    ];

    const RAG_ORDER = { 'no-data': 0, red: 1, amber: 2, green: 3 };

    // Gather current state
    let redCount = 0, amberCount = 0, greenCount = 0, noDataCount = 0;
    const improvements = [];
    const deteriorations = [];
    const streaks = [];

    TRACKED.forEach((name) => {
      const country = data.countries[name];
      if (!country) return;

      const entry = country.history.find((h) => h.date === reportDate);
      const rag = entry ? (entry.overall || 'no-data') : 'no-data';

      if (rag === 'red') redCount++;
      else if (rag === 'amber') amberCount++;
      else if (rag === 'green') greenCount++;
      else noDataCount++;

      // Check movement from previous report
      if (dateIndex > 0) {
        const prevDate = reports[dateIndex - 1];
        const prevEntry = country.history.find((h) => h.date === prevDate);
        const prevRag = prevEntry ? (prevEntry.overall || 'no-data') : 'no-data';

        if (RAG_ORDER[rag] > RAG_ORDER[prevRag]) {
          improvements.push({ name, from: prevRag, to: rag });
        } else if (RAG_ORDER[rag] < RAG_ORDER[prevRag]) {
          deteriorations.push({ name, from: prevRag, to: rag });
        }
      }

      // Consecutive streak
      let streak = 0;
      for (let i = country.history.length - 1; i >= 0; i--) {
        if ((country.history[i].overall || 'no-data') === rag) streak++;
        else break;
      }
      if (streak >= 3 && rag !== 'no-data') {
        streaks.push({ name, rag, count: streak });
      }
    });

    // Build insights object
    const insights = {
      date: reportDate,
      executive_summary: buildExecutiveSummary(redCount, amberCount, greenCount, noDataCount, improvements, deteriorations, TRACKED.length),
      trends: buildTrends(streaks, improvements, deteriorations),
      predictions: buildPredictions(streaks, improvements, data, reportDate),
      coaching: buildCoaching(streaks, redCount, amberCount, greenCount, improvements),
      risk_watch: buildRiskWatch(deteriorations, streaks),
    };

    renderInsightsFromData(container, insights);
  }

  function buildExecutiveSummary(red, amber, green, noData, improvements, deteriorations, total) {
    const parts = [];
    parts.push(`${total} countries tracked.`);

    if (red > 0) parts.push(`${red} Red.`);
    parts.push(`${amber} Amber, ${green} Green.`);

    if (red === 0) parts.push('No Red countries — positive signal.');

    if (improvements.length > 0) {
      const names = improvements.map((i) => `${i.name} (${cap(i.from)} \u2192 ${cap(i.to)})`);
      parts.push(`Improved: ${names.join(', ')}.`);
    }

    if (deteriorations.length > 0) {
      const names = deteriorations.map((d) => `${d.name} (${cap(d.from)} \u2192 ${cap(d.to)})`);
      parts.push(`Worsened: ${names.join(', ')}.`);
    }

    return parts.join(' ');
  }

  function buildTrends(streaks, improvements, deteriorations) {
    const trends = [];

    streaks.forEach((s) => {
      const severity = s.rag === 'green' ? 'positive' : s.rag === 'red' ? 'negative' : 'warning';
      trends.push({
        country: s.name,
        insight: `${cap(s.rag)} for ${s.count} consecutive reports. ${s.rag === 'amber' ? 'Persistent Amber may indicate systemic blockers preventing progress.' : s.rag === 'green' ? 'Stable and healthy.' : 'Sustained Red — needs immediate attention.'}`,
        severity,
      });
    });

    improvements.forEach((i) => {
      trends.push({
        country: i.name,
        insight: `Improved from ${cap(i.from)} to ${cap(i.to)}. Positive momentum.`,
        severity: 'positive',
      });
    });

    deteriorations.forEach((d) => {
      trends.push({
        country: d.name,
        insight: `Worsened from ${cap(d.from)} to ${cap(d.to)}. Investigate root cause.`,
        severity: 'negative',
      });
    });

    return trends;
  }

  function buildPredictions(streaks, improvements, data, currentDate) {
    const predictions = [];

    // Countries on upward trajectory
    improvements.forEach((i) => {
      if (i.to === 'green') {
        predictions.push({
          country: i.name,
          prediction: `Recently reached Green. If current stability holds, should maintain Green in next report.`,
          confidence: 'medium',
        });
      } else if (i.to === 'amber' && i.from === 'red') {
        predictions.push({
          country: i.name,
          prediction: `Improving from Red to Amber. Could reach Green in 2-3 reports if current momentum continues and blockers are resolved.`,
          confidence: 'medium',
        });
      }
    });

    // Long amber streaks
    streaks.filter((s) => s.rag === 'amber' && s.count >= 4).forEach((s) => {
      predictions.push({
        country: s.name,
        prediction: `Amber for ${s.count} consecutive reports. Without intervention, unlikely to reach Green this quarter.`,
        confidence: 'high',
      });
    });

    return predictions;
  }

  function buildCoaching(streaks, red, amber, green, improvements) {
    const coaching = [];

    if (improvements.length > 0) {
      const greenMoves = improvements.filter((i) => i.to === 'green');
      if (greenMoves.length > 0) {
        coaching.push(`${greenMoves.map((g) => g.name).join(' and ')} reached Green. Pattern: countries reach Green when support tickets hit zero AND no active blockers for 2+ weeks. Use this as a template.`);
      }
    }

    streaks.filter((s) => s.rag === 'amber' && s.count >= 4).forEach((s) => {
      coaching.push(`${s.name} has been Amber for ${s.count} reports. Consider: (1) dedicated sprint to burn down the backlog, (2) deprioritize and accept Amber while focusing resources on upcoming launches, or (3) reassign ownership to accelerate resolution.`);
    });

    if (red === 0 && amber > 5) {
      coaching.push(`No Red countries, but ${amber} remain Amber. The risk is "Amber fatigue" — when everything is Amber, nothing gets prioritized. Pick 2-3 countries to focus on pushing to Green.`);
    }

    if (coaching.length === 0) {
      coaching.push('Overall trajectory is positive. Focus on maintaining momentum and preventing regression in recently-improved countries.');
    }

    return coaching;
  }

  function buildRiskWatch(deteriorations, streaks) {
    const risks = [];

    deteriorations.forEach((d) => {
      risks.push(`${d.name} worsened from ${cap(d.from)} to ${cap(d.to)}. Investigate what changed and whether this is a temporary setback or systemic issue.`);
    });

    streaks.filter((s) => s.rag === 'red' && s.count >= 2).forEach((s) => {
      risks.push(`${s.name} has been Red for ${s.count} reports. Extended Red status often correlates with missed ETAs and escalation risk.`);
    });

    return risks;
  }

  function cap(s) {
    if (!s) return s;
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
})();
